settings:
  spawn: # Настройка спавна существ
    egg: true # Проверка спавна с помощью яйца призыва (раздатчик, обычное яйцо)
    spawner: true # Проверка спавна с помощью спавнера
    command: true # Проверка спавна с помощью команды
    another: true # Проверка спавна по других причинах
    maximum: # Настройка кол-во существ на чанк
      pig: 32 # Количество свиней на чанк
      default: 16 # Стандартное кол-во (если -1 то не ограничено)
      global: -1 # Максимальное кол-во существ на чанк (игнорируется существа blacklist)
    blacklist: # Список существ на которые лимит не распространяется (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html)
    - "WANDERING_TRADER" # странствующий торговец
messages:
  command: "&aКонфигурация была перезагружена"
  permission: "&cУ вас не достаточно прав!"